import { NgModule } from '@angular/core';
// import {
//   MatToolbarModule,
//   MatMenuModule,
//   MatIconModule,
//   MatButtonModule,
//   MatTableModule,
//   MatDividerModule,
//   MatProgressSpinnerModule,
//   MatInputModule,
//   MatCardModule,
//   MatSlideToggleModule,
//   MatSelectModule,
//   MatOptionModule,
//   MatCheckboxModule,
//   MatAutocompleteModule,
//   MatBadgeModule,
//   MatBottomSheetModule,
//   MatButtonToggleModule,
//   MatChipsModule,
//   MatStepperModule,
//   MatDatepickerModule,
//   MatDialogModule,
//   MatExpansionModule,
//   MatGridListModule,
//   MatListModule,
//   MatNativeDateModule,
//   MatPaginatorModule,
//   MatProgressBarModule,
//   MatRadioModule,
//   MatRippleModule,
//   MatTooltipModule,
//   MatTreeModule,
//   MatSidenavModule,
//   MatSliderModule,
//   MatSnackBarModule,
//   MatSortModule,
//   MatTabsModule

// } from '@angular/material';


@NgModule({
  declarations: [],
  imports: [

    // // MatToolbarModule,
    // // MatMenuModule,
    // // MatIconModule,
    // // MatButtonModule,
    // // MatTableModule,
    // // MatDividerModule,
    // // MatProgressSpinnerModule,
    // // MatInputModule,
    // // MatCardModule,
    // // MatSlideToggleModule,
    // // MatSelectModule,
    // // MatOptionModule,
    // // MatCheckboxModule,
    // // MatAutocompleteModule,
    // // MatBadgeModule,
    // // MatBottomSheetModule,
    // // MatButtonToggleModule,
    // // MatChipsModule,
    // // MatStepperModule,
    // // MatDatepickerModule,
    // // MatDialogModule,
    // // MatExpansionModule,
    // // MatGridListModule,
    // // MatListModule,
    // // MatNativeDateModule,
    // // MatPaginatorModule,
    // // MatProgressBarModule,
    // // MatRadioModule,
    // // MatRippleModule,
    // // MatTooltipModule,
    // // MatTreeModule,
    // // MatSidenavModule,
    // // MatSliderModule,
    // // MatSnackBarModule,
    // // MatSortModule,
    // // MatTabsModule
    // OverlayModule,
    // PortalModule,
    // ScrollingModule,

  ],
  exports: [
    // // MatToolbarModule,
    // // MatMenuModule,
    // // MatIconModule,
    // // MatButtonModule,
    // // MatTableModule,
    // // MatDividerModule,
    // // MatProgressSpinnerModule,
    // // MatInputModule,
    // // MatCardModule,
    // // MatSlideToggleModule,
    // // MatSelectModule,
    // // MatOptionModule,
    // // MatCheckboxModule,
    // // MatAutocompleteModule,
    // // MatBadgeModule,
    // // MatBottomSheetModule,
    // // MatButtonToggleModule,
    // // MatChipsModule,
    // // MatStepperModule,
    // // MatDatepickerModule,
    // // MatDialogModule,
    // // MatExpansionModule,
    // // MatGridListModule,
    // // MatListModule,
    // // MatNativeDateModule,
    // // MatPaginatorModule,
    // // MatProgressBarModule,
    // // MatRadioModule,
    // // MatRippleModule,
    // // MatTooltipModule,
    // // MatTreeModule,
    // // MatSidenavModule,
    // // MatSliderModule,
    // // MatSnackBarModule,
    // // MatSortModule,
    // // MatTabsModule

  ]
})
export class MaterialModule { }
